bank: Bank field should be not required on bank account model
coopengo/bank pull request #2
Opened 2021-05-20 13:18 UTC by GUERMASSI

Fi#19670

2021-05-20 13:47 UTC, JCavallo requested changes
Pour moi, la seule chose à faire ici, c'est faire "cls.bank.required = False" dans le setup

Avec un gros commentaire

Pour le reste, c'est dans bank_cog. on veut le moins de modifications dans le module standard

2021-05-20 15:15 UTC, GUERMASSI commented
@Jean done

2021-05-20 19:05 UTC, JCavallo approved these changes
Attendre que la PR soit mergée côté Coog

2021-05-21 10:18 UTC, jpyung approved these changes

2021-05-24 16:27 UTC, merged